name: EvergreenEntityEditor
version: '1.0.0'
main: ever.green.EntityEditor
api-version: '26.1'
authors: [ Lambrechts ]
softdepend: [GriefPrevention]

commands:
  ee:
    description: "Opens the unified Entity Editor hotbar"
    usage: "/ee"
    permission: evergreen.ee.use
    aliases: [entityeditor]

permissions:
  evergreen.ee.use:
    description: "Allows use of the /ee command and editor mode"
    default: op